// SPDX-License-Identifier: BSD-3-Clause

/*
 * Copyright (c) 2024 Cory Voltz <voltzc@twchl.net>
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * @include/voltos/bits.h (2024-08-25) - Generic bit functions
 */

#ifndef _VOLTOS_BITS_H_
#define _VOLTOS_BITS_H_

#include <stdbit.h>

#define BITS_PER_NIBBLE		4
#define BITS_PER_BYTE		8
#define BITS_PER_OCTET		8
#define BITS_PER_HEXTET		16

#define BITS_PER_VLAN_ID	12
#define BITS_PER_VNID		24

#define __bit_mask_u32(nr)			(UL(1) << ((nr) % 32))
#define __bit_word_u32(nr)			((nr) / 32)

#define __bit_mask_u64(nr)			(ULL(1) << ((nr) % 64))
#define __bit_word_u64(nr)			((nr) / 64)

#endif /* _VOLTOS_BITS_H_ */
