// SPDX-License-Identifier: BSD-3-Clause

/*
 * Copyright (c) 2024 Cory Voltz <voltzc@twchl.net>
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * @include/voltos/stdarg.h (2024-08-27) - Generic argument wrappers
 */

#ifndef _VOLTOS_STDARG_H_
#define _VOLTOS_STDARG_H_

#include <stdarg.h>

#define __va_start(v, l)			va_start(v, l)
#define __va_end(v)					va_end(v)
#define __va_arg(v, T)				va_arg(v, T)
#define __va_copy(d, s)				va_copy(d, s)

#endif /* _VOLTOS_STDARG_H_ */
